name: CI

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manually dispatching the CI when outside of main branch
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  # https://github.com/sanity-io/semantic-release-preset/actions/workflows/ci.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  next:
    name: Next.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci --ignore-scripts
      - run: npx vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
      - run: npm run build:web
      - run: npm run lint --if-present
      - run: npm run test --if-present

  studio:
    name: Studio
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./studio
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: studio/yarn.lock
      - run: yarn install --frozen-lockfile
      - run: npx vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }} .env.development
      - run: npm run build --if-present
      - run: npm run lint --if-present
      - run: npm run test --if-present
