name: 🤖 Auto Prettier ✨

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: template

jobs:
  run:
    name: Prettier if needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm install --ignore-scripts --only-dev
      - run: npx prettier --ignore-path .gitignore --cache --write .
      - uses: EndBug/add-and-commit@v9
        with:
          commit: --no-verify
          message: "chore(prettier): prettier --write --cache ."
